bofa_credit: 
  path: ../transactions/BoFA/Credit/currentTransaction_5201.csv
  skiprows: 0
  column_mapping: {"Posted Date": "Date", "Payee": "Description"}
    
bofa_debit: 
  path: ../transactions/BoFA/Debit/stmt.csv
  skiprows: 6
  column_mapping: {}

venmo: 
  path: ../transactions/Venmo/transaction_history.csv
  skiprows: 2
  column_mapping: {"Datetime": "Date", "Note": "Description", "Amount (total)": "Amount"}